### ISSUE TITLE
Missing Header information

### ISSUE THREAD

**Issue by dimmuboy** [dwainscheeren/lovelace-dwains-theme#16]
Hi,
I have no header information only title in home.

![image](https://user-images.githubusercontent.com/12607479/74517507-7dfd9d80-4f12-11ea-8e6f-8224ca8e9435.png)

But I catch some error with mobile app

![image](https://user-images.githubusercontent.com/12607479/74517545-91106d80-4f12-11ea-9aa4-f3fe6d41f11f.png)

Here is my config:
global.yaml
```
global:
  language: en
  weather: weather.dark_sky
  outside_temperature: sensor.dark_sky_temperature
  outside_humidity: sensor.dark_sky_humidity
  # alarm: alarm_control_panel.alarm_system
  # inside_temperature: climate.living_room
```
house_information.yaml
```
house_information:
  favorites:
    - entity:  binary_sensor.updater
      icon_on: fas:cloud-upload-alt
      icon_off: fas:cloud-upload-alt
    - entity: binary_sensor.snapshots_stale
      icon_on: fas:google-drive
      icon_off: fas:google-drive

  calendar:
    - calendar.holidays_in_slovakia
    - calendar.slovak_nameday
    - calendar.contacts
    - calendar.family
```
persons.yaml
```
persons: 
  - name: Luky
    track: person.luky
    picture_path: 'images/persons/luky.png'
  - name: Ladka
    track: person.ladka
    picture_path: 'images/persons/ladka.png'
```
