### ISSUE TITLE
[FR] Add tracking option to map

### ISSUE THREAD

**Issue by roblandry** [dwainscheeren/lovelace-dwains-theme#182]
Include an option "map_hours_to_show" in persons.yaml config and add this to views/main/persons/person.yaml Line 81:
```yaml
              {% if person["show_map"] != 'false' %}
              - type: map
                aspect_ratio: 16x9
                hours_to_show: |
                  {% if person["map_hours_to_show"] %}
                    {{ person["map_hours_to_show"]|int }}
                  {% else %}
                    0
                  {% endif %}
                entities:
                  - {{ person["track"] }}
              {% endif %}
```
in place of this:
```yaml
              {% if person["show_map"] != 'false' %}
              - type: map
                aspect_ratio: 16x9
                entities:
                  - {{ person["track"] }}
              {% endif %}
```
