### ISSUE TITLE
Trouble with binary sensor lock

### ISSUE THREAD

**Issue by totalitarian** [dwainscheeren/lovelace-dwains-theme#197]
I’ve converted a binary sensor to a lock using this binary sensor template (it's a dumb lock so I just detect the state - I can't remotely lock / unlock it)

```
      back_door_lock:
        friendly_name: "Back Door"
        device_class: lock
        value_template: >-
         {{ is_state('binary_sensor.lumi_lumi_sensor_magnet_aq2_ce212304_on_off', 'off') }}
```
I've added it to my room.yaml like so
```

  - name: Utility
    icon: mdi:washing-machine
    light: light.utility_light
    media_player: media_player.utility_speaker
    lock: binary_sensor.back_door_lock
```

But it doesn't appear on the devices / lock page. The room appears (Utility) but not the actual lock button.

![image](https://user-images.githubusercontent.com/2385696/92765081-ed464d80-f38c-11ea-9a44-9666227b7d56.png)

Is it because the domain still appears as` binary_sensor `rather than `lock`?

**Comment by totalitarian** [comment]
Solved it like so

Made a dummy script.


```
script:
  dummy:
    sequence:
      delay: "00:00:00"

```

`and a template lock
`

```
lock:
  - platform: template
    name: Garage door
    value_template: "{{ is_state('binary_sensor.lumi_lumi_sensor_magnet_aq2_ce212304_on_off', 'off') }}"
    lock:
      service: script.dummy
    unlock:
      service: script.dummy
```
