### ISSUE TITLE
[FR] Custom icons for input_select

### ISSUE THREAD

**Issue by haplm** [dwainscheeren/lovelace-dwains-theme#51]
Would it be possible to define single icon attribute for input_select which is on house_information page? Something like this:

```
house_information:
  favorites:
    - entity: input_select.heating_mode
      icon: fas:fire-alt
```

Right now it seems to support only binary sensors (possibly switches?) with on/off pair of icons...
