### ISSUE TITLE
Version 1.2.1 is not compatible with HA 1.107

### ISSUE THREAD

**Issue by janusloo** [dwainscheeren/lovelace-dwains-theme#56]
Hi,
I upgraded my HA to version 1.107 yesterday and your theme breaks. HA started in failsafe mode. If I disabled your theme, HA starts without any issues.

Are you aware of the breaking change in the latest version of HA? 
I just downgraded to version 1.106 until you have a fix for this. 
Thank you for your great theme!

**Comment by dwainscheeren** [comment]
Yes I also mentioned that multiple times in the HA forum thread, please don't upgrade to 0.107 for now it will break my theme.

**Comment by janusloo** [comment]
> Yes I also mentioned that multiple times in the HA forum thread, please don't upgrade to 0.107 for now it will break my theme.

Oh I am sorry, I didn't check the forum first. My apology if I wasted your time. 
Should I close the issue?

**Comment by joyka** [comment]
I managed to get 1.3.0 running with 0.107 in 2 simple steps

1) Add all resources from `/config/dwains-theme/resources/main.yaml` manually to HA (Configuration > Lovelace dashboards > Resources)
2) Change lovelace section of `/config/packages/dwains-theme/dwains_theme_configuration.yaml` to
```yaml
lovelace:
  mode: storage
  dashboards:
    dwains-theme:
      mode: yaml
      title: Dwains Theme
      icon: mdi:script
      show_in_sidebar: true
      filename: ui-lovelace.yaml
```
