### ISSUE TITLE
[FR] Hide top menu on addon pages

### ISSUE THREAD

**Issue by Tosko4** [dwainscheeren/lovelace-dwains-theme#77]
Hi,

I would like to have a feature that allows me to show/hide a header on an addon page. 

I am trying to run a floorplan on a wall monitor I have. But need full width and height of the screen to show it all without the header showing with the back button. 

The only way now is to remove that piece of code, but unfortunately removes it from all addon pages.

**Comment by dwainscheeren** [comment]
From version 1.4 you can use: `show_header: 'false'` in the addon and it won't show the header. This option is true by default.

Example:
```
    - name: Hello more page
      icon: fas:chart-area
      show_header: 'false'
      path: 'dwains-theme/addons/more_page/hello-more-page/page.yaml'
      data:
        some_data: 'This is some data parsed.'
        some_other_data: 'and some other data.'
````
